#!/usr/bin/env python3
"""Emit ipmi_sim commands that give the simulated BMC a sensor repository.

ipmi_sim only knows the sensors its config declares, and it wants the SDR
(Sensor Data Record) for each one as raw bytes. Hand-writing those is how
people get the byte offsets wrong, so this builds IPMI Full Sensor Records
(spec section 43.1) from a short table and prints the `sensor_add` /
`sensor_set_threshold` / `sensor_set_event_support` / `main_sdr_add` lines
that go in sim.emu.in. The committed sim.emu.in was generated by:

    python3 deploy/sim/gen_sensors.py >> deploy/sim/sim.emu.in

Each sensor polls its reading from a file, `@STATE@/sensors/<hex number>`,
once a second (run-sim.sh substitutes the state directory and writes the
initial values with `--write-values`). Two reasons: OpenIPMI 2.0.37 only
marks a sensor readable through its polling path, so values set statically
in the config never show on Ubuntu 26.04; and a file is something a person
can edit to simulate a fault:

    echo 96 > /var/lib/doz/sim/sensors/30      # CPU1 Temp to 96 C: critical
    echo 0  > /var/lib/doz/sim/sensors/40      # FAN1 stalls: critical, SEL event

Files hold the value in the sensor's own unit (degrees C, RPM, millivolts,
watts); `div=` turns it into the raw byte the SDR describes.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

MC = 0x20
POLL_MS = 1000

#: Sensor type codes (IPMI table 42-3) and base units (table 43-15).
TEMPERATURE, VOLTAGE, FAN, PSU = 0x01, 0x02, 0x04, 0x08
DEG_C, VOLTS, WATTS, RPM = 0x01, 0x04, 0x06, 0x12
#: Entity IDs (table 43-13).
PROCESSOR, SYSTEM_BOARD, POWER_SUPPLY, FAN_DEVICE, MEMORY = 0x03, 0x07, 0x0A, 0x1D, 0x08

# name, number, sensor type, unit, entity, entity instance, initial value in
# the unit, thresholds in the unit as (unr, uc, unc, lnc, lc, lnr), None = n/a
SENSORS = [
    ("CPU1 Temp", 0x30, TEMPERATURE, DEG_C, PROCESSOR, 1, 47, (100, 95, 85, None, None, None)),
    ("CPU2 Temp", 0x31, TEMPERATURE, DEG_C, PROCESSOR, 2, 44, (100, 95, 85, None, None, None)),
    ("Inlet Temp", 0x32, TEMPERATURE, DEG_C, SYSTEM_BOARD, 1, 23, (55, 50, 45, None, None, None)),
    ("DIMM Temp", 0x33, TEMPERATURE, DEG_C, MEMORY, 1, 38, (95, 90, 85, None, None, None)),
    ("FAN1 Tach", 0x40, FAN, RPM, FAN_DEVICE, 1, 4200, (None, None, None, 1500, 1000, 500)),
    ("FAN2 Tach", 0x41, FAN, RPM, FAN_DEVICE, 2, 4100, (None, None, None, 1500, 1000, 500)),
    ("FAN3 Tach", 0x42, FAN, RPM, FAN_DEVICE, 3, 4300, (None, None, None, 1500, 1000, 500)),
    ("P12V", 0x50, VOLTAGE, VOLTS, SYSTEM_BOARD, 1, 12100, (None, 13200, 12800, 11200, 10800, None)),
    ("P3V3", 0x51, VOLTAGE, VOLTS, SYSTEM_BOARD, 1, 3300, (None, 3600, 3500, 3100, 3000, None)),
    ("VBAT", 0x52, VOLTAGE, VOLTS, SYSTEM_BOARD, 1, 3000, (None, None, None, 2600, 2400, None)),
    ("PSU1 Power", 0x60, PSU, WATTS, POWER_SUPPLY, 1, 185, (None, 250, 230, None, None, None)),
    ("PSU2 Power", 0x61, PSU, WATTS, POWER_SUPPLY, 2, 0, (None, 250, 230, None, None, None)),
]

#: Unit -> (M, R-exponent, file divisor). reading = raw * M * 10**R, and
#: raw = file value / divisor. Fans count in hundreds of RPM, volts in tenths
#: (so the file holds millivolts), the rest are one byte per unit.
SCALE = {RPM: (1, 2, 100), VOLTS: (1, -1, 100), DEG_C: (1, 0, 1), WATTS: (1, 0, 1)}


def raw(unit: int, value: int | None) -> int | None:
    if value is None:
        return None
    _m, _r, div = SCALE[unit]
    return round(value / div)


def full_sensor_record(
    name: str,
    number: int,
    sensor_type: int,
    unit: int,
    entity: int,
    instance: int,
    thresholds: tuple[int | None, ...],
) -> bytes:
    m, r_exp, _div = SCALE[unit]
    unr, uc, unc, lnc, lc, lnr = (raw(unit, t) for t in thresholds)
    readable = 0
    for bit, value in enumerate((lnc, lc, lnr, unc, uc, unr)):
        if value is not None:
            readable |= 1 << bit

    body = bytearray()
    body += bytes([MC, 0x00, number])  # owner id, owner LUN, sensor number
    body += bytes([entity, instance])
    body += bytes([0x7F])  # init: scanning + events on, thresholds settable
    body += bytes([0x68])  # capabilities: auto re-arm, thresholds readable+settable
    body += bytes([sensor_type, 0x01])  # event/reading type: threshold
    body += bytes([0x00, 0x00, 0x00, 0x00])  # assertion / deassertion masks
    body += bytes([readable, readable])  # settable / readable threshold masks
    body += bytes([0x00, unit, 0x00])  # units 1 (unsigned), base unit, modifier
    body += bytes([0x00])  # linearization: linear
    body += bytes([m & 0xFF, (m >> 8 & 0x03) << 6])  # M, M-MS + tolerance
    body += bytes([0x00, 0x00, 0x00])  # B, B-MS + accuracy, accuracy MS + direction
    body += bytes([(r_exp & 0x0F) << 4])  # R exponent, B exponent
    body += bytes([0x00, 0x00, 0x00, 0x00])  # analog flags, nominal, normal max/min
    body += bytes([0xFF, 0x00])  # sensor max / min
    body += bytes([v or 0 for v in (unr, uc, unc, lnr, lc, lnc)])
    body += bytes([0x00, 0x00])  # hysteresis
    body += bytes([0x00, 0x00, 0x00])  # reserved, reserved, OEM
    encoded = name.encode("ascii")
    body += bytes([0xC0 | len(encoded)]) + encoded

    header = bytes([0x00, 0x00, 0x51, 0x01, len(body)])
    return header + bytes(body)


def emu_lines() -> list[str]:
    out = ["# --- sensors (generated by gen_sensors.py; values polled from @STATE@/sensors/) ---"]
    for name, number, stype, unit, entity, instance, _value, thresholds in SENSORS:
        _m, _r, div = SCALE[unit]
        out.append(
            f"sensor_add {MC:#x} 0 {number:#x} {stype:#x} 0x01 "
            f'poll {POLL_MS} file "@STATE@/sensors/{number:02x}" base=10 div={div}'
        )
        unr, uc, unc, lnc, lc, lnr = thresholds
        enabled = "".join("1" if v is not None else "0" for v in (unr, uc, unc, lnc, lc, lnr))
        values = " ".join(f"{(raw(unit, v) or 0):#x}" for v in (unr, uc, unc, lnc, lc, lnr))
        out.append(f"sensor_set_threshold {MC:#x} 0 {number:#x} settable {enabled} {values}")
        record = full_sensor_record(name, number, stype, unit, entity, instance, thresholds)
        out.append(f"main_sdr_add {MC:#x} " + " ".join(f"{b:#04x}" for b in record))
    # Events and scanning on. These must come after every main_sdr_add:
    # ipmi_sim silently drops SDRs added after a sensor's event support has
    # been set (measured, 1.0.13).
    masks = " ".join(["000111111000111111"] * 4)
    for _name, number, *_rest in SENSORS:
        out.append(
            f"sensor_set_event_support {MC:#x} 0 {number:#x} enable scanning per-state {masks}"
        )
    return out


def write_values(directory: Path, *, overwrite: bool = False) -> int:
    """Create the value files the polled sensors read. Returns how many were written."""
    directory.mkdir(parents=True, exist_ok=True)
    written = 0
    for _name, number, _stype, _unit, _entity, _instance, value, _thresholds in SENSORS:
        path = directory / f"{number:02x}"
        if path.exists() and not overwrite:
            continue
        path.write_text(f"{value}\n")
        written += 1
    return written


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write-values", metavar="DIR", type=Path,
                        help="write the initial sensor value files into DIR instead")
    parser.add_argument("--reset", action="store_true",
                        help="with --write-values: overwrite files that already exist")
    args = parser.parse_args()
    if args.write_values:
        n = write_values(args.write_values, overwrite=args.reset)
        print(f"{n} sensor value files written to {args.write_values}", file=sys.stderr)
    else:
        print("\n".join(emu_lines()))
