#!/usr/bin/env python3
"""Emit ipmi_sim commands that give the simulated BMC a sensor repository.

ipmi_sim only knows the sensors its config declares, and it wants the SDR
(Sensor Data Record) for each one as raw bytes. Hand-writing those is how
people get the byte offsets wrong, so this builds IPMI Full Sensor Records
(spec section 43.1) from a short table and prints the `sensor_add` /
`sensor_set_value` / `sensor_set_threshold` / `main_sdr_add` lines that go
in sim.emu. The committed sim.emu was generated by:

    python3 deploy/sim/gen_sensors.py >> deploy/sim/sim.emu

Readings use M=1, B=0 with no exponents, so raw value == displayed value.
"""

from __future__ import annotations

MC = 0x20

#: Sensor type codes (IPMI table 42-3) and base units (table 43-15).
TEMPERATURE, VOLTAGE, FAN, PSU = 0x01, 0x02, 0x04, 0x08
DEG_C, VOLTS, WATTS, RPM = 0x01, 0x04, 0x06, 0x12
#: Entity IDs (table 43-13).
PROCESSOR, SYSTEM_BOARD, POWER_SUPPLY, FAN_DEVICE, MEMORY = 0x03, 0x07, 0x0A, 0x1D, 0x08

# name, number, sensor type, unit, entity, (entity instance), value,
# thresholds as (unr, uc, unc, lnc, lc, lnr) -- None when not applicable
SENSORS = [
    ("CPU1 Temp", 0x30, TEMPERATURE, DEG_C, PROCESSOR, 1, 47, (100, 95, 85, None, None, None)),
    ("CPU2 Temp", 0x31, TEMPERATURE, DEG_C, PROCESSOR, 2, 44, (100, 95, 85, None, None, None)),
    ("Inlet Temp", 0x32, TEMPERATURE, DEG_C, SYSTEM_BOARD, 1, 23, (55, 50, 45, None, None, None)),
    ("DIMM Temp", 0x33, TEMPERATURE, DEG_C, MEMORY, 1, 38, (95, 90, 85, None, None, None)),
    ("FAN1 Tach", 0x40, FAN, RPM, FAN_DEVICE, 1, 42, (None, None, None, 15, 10, 5)),
    ("FAN2 Tach", 0x41, FAN, RPM, FAN_DEVICE, 2, 41, (None, None, None, 15, 10, 5)),
    ("FAN3 Tach", 0x42, FAN, RPM, FAN_DEVICE, 3, 43, (None, None, None, 15, 10, 5)),
    ("P12V", 0x50, VOLTAGE, VOLTS, SYSTEM_BOARD, 1, 121, (None, 132, 128, 112, 108, None)),
    ("P3V3", 0x51, VOLTAGE, VOLTS, SYSTEM_BOARD, 1, 33, (None, 36, 35, 31, 30, None)),
    ("VBAT", 0x52, VOLTAGE, VOLTS, SYSTEM_BOARD, 1, 30, (None, None, None, 26, 24, None)),
    ("PSU1 Power", 0x60, PSU, WATTS, POWER_SUPPLY, 1, 185, (None, 250, 230, None, None, None)),
    ("PSU2 Power", 0x61, PSU, WATTS, POWER_SUPPLY, 2, 0, (None, 250, 230, None, None, None)),
]

#: Which sensors report in tenths (fans in hundreds) so values fit in a byte.
#: (M, R-exponent): reading = raw * M * 10**R.
SCALE = {RPM: (1, 2), VOLTS: (1, -1)}


def full_sensor_record(
    name: str,
    number: int,
    sensor_type: int,
    unit: int,
    entity: int,
    instance: int,
    thresholds: tuple[int | None, ...],
) -> bytes:
    m, r_exp = SCALE.get(unit, (1, 0))
    unr, uc, unc, lnc, lc, lnr = thresholds
    readable = 0
    for bit, value in enumerate((lnc, lc, lnr, unc, uc, unr)):
        if value is not None:
            readable |= 1 << bit

    body = bytearray()
    body += bytes([MC, 0x00, number])  # owner id, owner LUN, sensor number
    body += bytes([entity, instance])
    body += bytes([0x7F])  # init: scanning + events on, thresholds settable
    body += bytes([0x68])  # capabilities: auto re-arm, thresholds readable+settable
    body += bytes([sensor_type, 0x01])  # event/reading type: threshold
    body += bytes([0x00, 0x00, 0x00, 0x00])  # assertion / deassertion masks
    body += bytes([readable, readable])  # settable / readable threshold masks
    body += bytes([0x00, unit, 0x00])  # units 1 (unsigned), base unit, modifier
    body += bytes([0x00])  # linearization: linear
    body += bytes([m & 0xFF, (m >> 8 & 0x03) << 6])  # M, M-MS + tolerance
    body += bytes([0x00, 0x00, 0x00])  # B, B-MS + accuracy, accuracy MS + direction
    body += bytes([(r_exp & 0x0F) << 4])  # R exponent, B exponent
    body += bytes([0x00, 0x00, 0x00, 0x00])  # analog flags, nominal, normal max/min
    body += bytes([0xFF, 0x00])  # sensor max / min
    body += bytes([v or 0 for v in (unr, uc, unc, lnr, lc, lnc)])
    body += bytes([0x00, 0x00])  # hysteresis
    body += bytes([0x00, 0x00, 0x00])  # reserved, reserved, OEM
    encoded = name.encode("ascii")
    body += bytes([0xC0 | len(encoded)]) + encoded

    header = bytes([0x00, 0x00, 0x51, 0x01, len(body)])
    return header + bytes(body)


def emu_lines() -> list[str]:
    out = ["# --- sensors (generated by gen_sensors.py) ---"]
    for name, number, stype, unit, entity, instance, value, thresholds in SENSORS:
        out.append(f"sensor_add {MC:#x} 0 {number:#x} {stype:#x} 0x01")
        out.append(f"sensor_set_value {MC:#x} 0 {number:#x} {value:#x} 0")
        unr, uc, unc, lnc, lc, lnr = thresholds
        enabled = "".join("1" if v is not None else "0" for v in (unr, uc, unc, lnc, lc, lnr))
        values = " ".join(f"{(v or 0):#x}" for v in (unr, uc, unc, lnc, lc, lnr))
        out.append(f"sensor_set_threshold {MC:#x} 0 {number:#x} settable {enabled} {values}")
        record = full_sensor_record(name, number, stype, unit, entity, instance, thresholds)
        out.append(f"main_sdr_add {MC:#x} " + " ".join(f"{b:#04x}" for b in record))
    # Scanning on, so Get Sensor Reading returns a value instead of "Disabled".
    # These must come after every main_sdr_add: ipmi_sim silently drops SDRs
    # added after a sensor's event support has been set (measured, 1.0.13).
    masks = " ".join(["000111111000111111"] * 4)
    for _name, number, *_rest in SENSORS:
        out.append(
            f"sensor_set_event_support {MC:#x} 0 {number:#x} enable scanning per-state {masks}"
        )
    return out


if __name__ == "__main__":
    print("\n".join(emu_lines()))
