#!/usr/bin/env bash
# A pretend C220 BMC on this machine, for trying the platform without hardware.
#
# Runs OpenIPMI's ipmi_sim -- a real IPMI-over-LAN (RMCP+) implementation --
# with a chassis hook that remembers power state and boot device, and a fake
# serial port that prints a POST screen and a Linux login on power-on/reset.
# ipmitool, and so the whole platform, cannot tell it from a BMC for the
# things that matter here: power on/off/reset/cycle, boot device, the
# Serial-over-LAN console, sensors (sim.emu.in, generated by gen_sensors.py),
# the event log, the identify LED, and user management.
#
#   run-sim.sh start [--user U] [--password P] [--port 9623] [--serial-port 9603] [--state DIR]
#   run-sim.sh stop | status
#   run-sim.sh events          add sample entries to the simulated event log
#
# Needs: ipmi_sim (apt install openipmi), ipmitool, python3.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE="${DOZ_SIM_STATE:-$HERE/../../.run/sim}"
ADDR=127.0.0.1
IPMI_PORT=9623
SERIAL_PORT=9603
USER_NAME=admin
PASSWORD=sim-password

cmd="${1:-status}"; shift || true
while [ $# -gt 0 ]; do
    case "$1" in
        --user)     USER_NAME="$2"; shift 2 ;;
        --password) PASSWORD="$2"; shift 2 ;;
        --port)     IPMI_PORT="$2"; shift 2 ;;
        --serial-port) SERIAL_PORT="$2"; shift 2 ;;
        --addr)     ADDR="$2"; shift 2 ;;
        --state)    STATE="$2"; shift 2 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done
mkdir -p "$STATE"
STATE="$(cd "$STATE" && pwd)"

running() { [ -f "$STATE/$1.pid" ] && kill -0 "$(cat "$STATE/$1.pid")" 2>/dev/null; }

ipmi() {
    IPMI_PASSWORD="$PASSWORD" ipmitool -I lanplus -H "$ADDR" -p "$IPMI_PORT" -U "$USER_NAME" \
        -E -C 3 -N 1 -R 1 "$@" 2>/dev/null
}

# ipmi_sim loads the sensors from the config but leaves their scanning
# switched off on a clean start, so every reading comes back "Disabled".
# Switch it on the way an OS would: Set Sensor Event Enable (NetFn 0x04,
# cmd 0x28) with scanning and events enabled, for every sensor the SDR
# lists. Then wait for the first poll of the value files to land.
enable_sensors() {
    for id in $(ipmi sdr elist | awk -F'|' '{gsub(/ /,"",$2); sub(/h$/,"",$2); print $2}'); do
        ipmi raw 0x04 0x28 "0x$id" 0xc0 >/dev/null 2>&1 || true
    done
    for _ in $(seq 1 10); do
        if ! ipmi sdr elist | grep -q -E "No Reading|Disabled"; then return 0; fi
        sleep 0.5
    done
    echo "warning: some sensors have no reading yet; see $STATE/ipmi_sim.log" >&2
}

stop() {
    for name in ipmi_sim serial; do
        if running "$name"; then
            kill "$(cat "$STATE/$name.pid")" 2>/dev/null || true
            echo "stopped $name"
        fi
        rm -f "$STATE/$name.pid"
    done
}

case "$cmd" in
    start)
        command -v ipmi_sim >/dev/null || { echo "ipmi_sim not found: sudo apt install openipmi" >&2; exit 1; }
        command -v ipmitool >/dev/null || { echo "ipmitool not found: sudo apt install ipmitool" >&2; exit 1; }
        stop >/dev/null
        [ -f "$STATE/power" ] || echo 1 > "$STATE/power"
        sed -e "s|@ADDR@|$ADDR|; s|@IPMI_PORT@|$IPMI_PORT|; s|@SERIAL_PORT@|$SERIAL_PORT|" \
            -e "s|@HERE@|$HERE|; s|@USER@|$USER_NAME|; s|@PASSWORD@|$PASSWORD|" \
            "$HERE/lan.conf.in" > "$STATE/lan.conf"
        chmod 600 "$STATE/lan.conf"

        SIM_STATE="$STATE" setsid python3 "$HERE/fake_serial.py" "$SERIAL_PORT" \
            > "$STATE/serial.log" 2>&1 < /dev/null &
        echo $! > "$STATE/serial.pid"
        sleep 0.5
        # A serial port that failed to bind would leave ipmi_sim's SOL talking
        # to whatever else is on that port -- a silently wrong simulator.
        if ! running serial; then
            echo "fake serial port could not start on $SERIAL_PORT:" >&2
            tail -3 "$STATE/serial.log" >&2
            exit 1
        fi

        # ipmi_sim persists its SDR repository under the state directory and
        # loads it on top of the config, so every restart would add a second
        # copy of each sensor. The config is the source of truth; start clean.
        rm -rf "$STATE/ipmi_sim"
        # Sensors poll their readings from files, one per sensor, so a reading
        # can be changed by hand to simulate a fault (see gen_sensors.py).
        # Existing values are kept across restarts.
        python3 "$HERE/gen_sensors.py" --write-values "$STATE/sensors" 2>/dev/null
        sed -e "s|@STATE@|$STATE|g" "$HERE/sim.emu.in" > "$STATE/sim.emu"
        SIM_STATE="$STATE" setsid ipmi_sim -c "$STATE/lan.conf" -f "$STATE/sim.emu" -s "$STATE" -n \
            > "$STATE/ipmi_sim.log" 2>&1 < /dev/null &
        echo $! > "$STATE/ipmi_sim.pid"

        for _ in $(seq 1 20); do
            if ipmi chassis power status >/dev/null 2>&1; then
                enable_sensors
                echo "BMC simulator up: IPMI on $ADDR:$IPMI_PORT, user $USER_NAME"
                echo "state in $STATE"
                exit 0
            fi
            sleep 0.5
        done
        echo "simulator did not answer; see $STATE/ipmi_sim.log" >&2
        exit 1
        ;;
    events)
        # Put a few entries in the System Event Log, the way a BMC would after
        # a fan stall and recovery, so the event log page has something to show.
        # Add SEL Entry (NetFn 0x0a, cmd 0x44) with a 16-byte system event
        # record; the simulator stamps its own time.
        ipmi raw 0x0a 0x44 0x00 0x00 0x02 0 0 0 0 0x20 0x00 0x04 0x01 0x32 0x01 0x57 0x33 0x2d >/dev/null
        ipmi raw 0x0a 0x44 0x00 0x00 0x02 0 0 0 0 0x20 0x00 0x04 0x04 0x40 0x01 0x52 0x00 0x0a >/dev/null
        ipmi raw 0x0a 0x44 0x00 0x00 0x02 0 0 0 0 0x20 0x00 0x04 0x04 0x40 0x81 0x52 0x2a 0x0a >/dev/null
        echo "added 3 events to the SEL"
        ;;
    stop)
        stop ;;
    status)
        for name in ipmi_sim serial; do
            if running "$name"; then echo "$name: running"; else echo "$name: stopped"; fi
        done
        [ -d "$STATE/sensors" ] && echo "sensor values: $STATE/sensors/<number> (edit to simulate a fault)"
        [ -f "$STATE/power" ] && echo "power: $( [ "$(cat "$STATE/power")" = 1 ] && echo on || echo off)"
        [ -f "$STATE/boot" ] && echo "boot device: $(cat "$STATE/boot")"
        ;;
    *)
        echo "usage: run-sim.sh start|stop|status|events" >&2; exit 2 ;;
esac
